### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by imSunnyk** [jinga-lala/Secure-Personal-Cloud#5]
Which python version have been used?

**Comment by imSunnyk** [comment]
Only in Linux system, can it be executed?

And how to start the web client ?

**Comment by jinga-lala** [comment]
Hi @imSunnyk,
Thanks for taking interest in our project. 
The project was developed in python3.6. We have tested our project on Linux system only. 
To start the web client you have to first run the server using `python3 manage.py runserver` then browse the webclient at `<server>/login` url. If the server is local then `<server>=127.0.0.1:8000`

After starting the webclient you need to create an account and then use linux CLI to login, generate a key, enter the key in webclient  and sync your desired directory on the server.
Useful commands:
`spc #logs you in the cloud`
`spc help #gives you a list of commands`
`man spc`
